### ISSUE TITLE
匯入 ivoting_schema.sql 發生錯誤

### ISSUE THREAD

**Issue by danny50610** [taipeicity/i-voting#1]
我按照`安裝手冊.pdf`的 4.4 步驟匯入 `ivoting_schema.sql` 時發生錯誤

錯誤訊息截圖如下：
![242](https://user-images.githubusercontent.com/3949245/29013417-94cea716-7b75-11e7-906b-1617e6a52688.png)

安裝 Joomla 的時候，有把資料表前綴改成跟 `ivoting_schema.sql` 一樣都是 `efa_`

**Comment by Taipeivoting** [comment]
您好

此訊息不影響此元件安裝，為避免此問題，我們也更新ivoting_schema.sql檔案。
由於目前功能尚未完全公開，所以仍會出現非預期錯誤，請詳閱NOTICE.TXT。

**Comment by danny50610** [comment]
雖然可以成功匯入了，不過功能似乎還不能使用
期待功能完全公開的那一天
