### ISSUE TITLE
安裝時發生問題，缺資料庫表格

### ISSUE THREAD

**Issue by aswebtw** [taipeicity/i-voting#2]
安裝過程中，出現錯誤訊息[Table 'joomla.#__unit' doesn't exist]，逐項檢查安裝手冊，確認沒有疏漏步驟，錯誤訊息依據git上的v1.3與最新版的v1.4比對，是缺少一個資料表，查看git上的ivoting_schema.sql確定沒有這個資料表。

請協助檢查，謝謝

**Comment by efatek** [comment]
@aswebtw 您好，針對缺少的unit資料表，已更新在[ #59bd86b](https://github.com/taipeicity/i-voting/blob/59bd86b1a4dd51e48d439071b6986467e3a69862/ivoting_schema.sql) 補上
